// New packs. "From scratch" builds the starter (src/core/starter/, generated by
// scripts/make-starter.mjs): a small, valid, playable two-side pack with generic
// names and the WW2 pack's measured numbers. "From an existing pack" clones one
// under a new id.

import { PackDocument, type FileMap } from './document'
import { starfieldPng } from './png'
import { renameUsages } from './refs'
import characters from './starter/characters.json'
import display from './starter/display.json'
import facilities from './starter/facilities.json'
import factions from './starter/factions.json'
import map from './starter/map.json'
import missionTables from './starter/mission_tables.json'
import missions from './starter/missions.json'
import rules from './starter/rules.json'
import setup from './starter/setup.json'
import units from './starter/units.json'
import weapons from './starter/weapons.json'

export interface StarterOptions {
  id: string
  displayName: string
  summary?: string
  /** Optional ids and names for the two sides (default faction_a / faction_b). */
  sides?: { id: string; displayName: string }[]
}

const enc = new TextEncoder()
const json = (v: unknown) => enc.encode(JSON.stringify(v, null, 2) + '\n')

export function starterFiles(opts: StarterOptions): FileMap {
  const pack = {
    id: opts.id,
    display_name: opts.displayName,
    summary: opts.summary ?? 'A new faction pack.',
    schema_version: 1,
    faction_count: 2,
    neutral: { id: 'neutral', display_name: 'Neutral', color: '#9a9a9a' },
    unexplored_color: '#cccccc',
    map_image: 'map.png',
    map_image_rect: [0, 0, 700, 420],
    setup: { difficulty_default: 'easy', galaxy_sizes: ['standard', 'large', 'huge'], galaxy_size_default: 'standard' },
    victory_tips: {
      standard: 'Win Conditions: Capture the enemy headquarters and the enemy leader and commander.',
      hq_only: 'Win Conditions: Capture the enemy headquarters.'
    }
  }
  const files: FileMap = new Map([
    ['pack.json', json(pack)],
    ['factions.json', json(factions)],
    ['map.json', json(map)],
    ['characters.json', json(characters)],
    ['facilities.json', json(facilities)],
    ['units.json', json(units)],
    ['weapons.json', json(weapons)],
    ['missions.json', json(missions)],
    ['mission_tables.json', json(missionTables)],
    ['rules.json', json(rules)],
    ['setup.json', json(setup)],
    ['display.json', json(display)],
    ['map.png', starfieldPng(700, 420, 7)]
  ])
  return files
}

/** A new, unsaved pack from the starter. Side ids/names are applied as renames so
 * every reference (rules, side lottery, rosters) follows. */
export function createStarterPack(opts: StarterOptions): PackDocument {
  const doc = new PackDocument(starterFiles(opts), null)
  const defaults = ['faction_a', 'faction_b']
  if (opts.sides) {
    doc.edit('Name the sides', (e) => {
      opts.sides!.forEach((side, i) => {
        const old = defaults[i]
        if (!side) return
        if (side.displayName) {
          e.set('factions.json', ['factions', i, 'display_name'], side.displayName)
          e.set('factions.json', ['factions', i, 'loyalty_label'], `Support for ${side.displayName}`)
        }
        if (side.id && side.id !== old) {
          renameUsages(doc, e, 'faction', old, side.id)
          e.set('factions.json', ['factions', i, 'id'], side.id)
        }
      })
    })
  }
  return asNew(doc)
}

/** A copy of `source` under a new id: every file, the id changed, nothing else -
 * except anything under original/, which is never pack content (the game refuses
 * a pack carrying it), so a copy made to be modded can always be exported. */
export function clonePack(source: PackDocument, id: string, displayName?: string): PackDocument {
  const files: FileMap = new Map()
  for (const f of source.allFiles()) if (!f.path.toLowerCase().startsWith('original/')) files.set(f.path, f.bytes)
  const doc = new PackDocument(files, null)
  doc.edit('New id', (e) => {
    e.set('pack.json', ['id'], id)
    if (displayName) e.set('pack.json', ['display_name'], displayName)
  })
  return asNew(doc)
}

/** A document with no undo history that saves as a brand-new folder. */
function asNew(doc: PackDocument): PackDocument {
  const files: FileMap = new Map()
  for (const f of doc.allFiles()) files.set(f.path, f.bytes)
  const fresh = new PackDocument(files, null)
  fresh.isNew = true
  return fresh
}
